
package org.oasis_open.docs.wsrf.rw_2;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.1.0
 * Generated source version: 4.1.0
 */

public class ResourceUnknownFault extends Exception {
}
